config/routes.rb
Rails.application.routes.draw do

  root 'photos#index'

  delete 'photos/:id' => 'photos#destroy'

  get 'photos' => 'photos#index'

  post 'photos' => 'photos#create'

  patch 'photos/:id' => 'photos#update'

  get 'photos/:id/edit' => 'photos#edit', as: "edit_photo"

  get 'photos/new' => 'photos#new'   # why this cant be behind the show method?

  get 'photos/:id' => 'photos#show', as: "photo"

  resources :pictures

end

app/models/photo.rb
class Photo < ActiveRecord::Base
end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end



  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_url
    else
      render :new
    end

  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update    ## the edit form will go to this update automatically? Since no method was indicated in the form
    @photo = Photo.find(params[:id])
    if @photo.update_attributes(photo_params)
      redirect_to photo_path(@photo)
    else
      render :edit
    end

  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to photos_url
  end

  def photo_params
    params.require(:photo).permit(:theme, :description, :url)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end



  def show
    @picture = Picture.find(params[:id])
  end

  def new
    @picture = Picture.new

  end

  def create
    # render :text => "Saving a picture. URL: #{params[:url]}, Title: #{params[:title]}, Artist: #{params[:artist]}"
    @picture = Picture.new(picture_params)
      if @picture.save
        redirect_to pictures_url
      else
        render :new
      end
  end

  def edit
    @picture = Picture.find(params[:id])

  end

  def update
    @picture = Picture.find(params[:id])
    if @picture.update_attributes(picture_params)
      redirect_to "/pictures/#{@picture.id}"
    else
      render :edit
    end

  end

  def destroy                                   # why when this method was moved to the end of this file doesnt work?
   @picture = Picture.find(params[:id])
   @picture.destroy
   redirect_to pictures_url
  end

  private              #??
  def picture_params
    params.require(:picture).permit(:artist, :title, :url)
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/edit.html.erb
<h1>Edit Photo</h1>
<p> <%= link_to "Back to the photo", photo_path(@photo) %> </p>
<p> <%= link_to "Back to Photo Gallery", photos_url %> </p>

<%= form_for @photo do |t| %>
<p>
  <%= t.label :theme %>
  <%= t.text_field :theme %>
</p>
<p>
  <%= t.label :description %>
  <%= t.text_field :description %>
</p>
<p>
  <%= t.label :url %>
  <%= t.text_field :url %>
</p>
<p>
  <%= t.submit "update" %>
</p>
<% end %>

app/views/photos/index.html.erb
<h1>Photos Gallery (<%= @photos.length %>)</h1>
<h3><%= link_to "Add New Collection", "/photos/new" %></h3>
<% @photos.each do |t| %>
<p><%= t.theme %>, <%= t.description %></p>
<%= link_to image_tag(t.url), photo_path(t.id) %>
<% end %>

app/views/photos/new.html.erb
<h1>Add a New Photo</h1>
<p> <%= link_to "Back to Photo Gallery", photos_url %> </p>

<%= form_for @photo do |t| %>
<p>
  <%= t.label :theme %>
  <%= t.text_field :theme %>
</p>
<p>
  <%= t.label :description %>
  <%= t.text_field :description %>
</p>
<p>
  <%= t.label :url %>
  <%= t.text_field :url %>
</p>
<p>
  <%= t.submit "Add Photo" %>
</p>
<% end %>

app/views/photos/show.html.erb
<h2>Theme:</h2>
<p><strong><%= @photo.theme %></strong></p>
<h3>Desciption:</h3>
<p><%= @photo.description %></p>
<p> <%= link_to "Back to Photo Gallery", photos_url %> | <%= link_to "Edit", edit_photo_path %> | <%= link_to "Delete", @photo, method: :delete, data: {confirm: "Are you sure to delete this photo collection?"} %></p>
<%= image_tag @photo.url %>

app/views/pictures/edit.html.erb
<h1>Edit a Picture</h1>
<p>
  <%= link_to "Back", @picture %>
</p>
<%= form_for @picture do |f| %>
  <p>
    <%= f.label :artist %> <br>
    <%= f.text_field :artist %>

  </p>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>

  </p>
  <p>
    <%= f.label :url %> <br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/pictures/index.html.erb
<h1>Pictures (<%= @pictures.length %>)</h1>

<%= link_to "Add new picture", "/pictures/new" %>


<% @pictures.each do |picture| %>
  <p><%= picture.title %>, <%=picture.artist %></p>
  <!-- <a href="/pictures/<%= picture.id %>"><img src="<%= picture.url %>"></a> -->
  <%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>

<%= link_to "Back to pictures", pictures_url %>
<%= form_for @picture do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", "/pictures" %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"} %>
<% # pictures_url          pictures/@picture.id    %>
<p><%= @picture.title %>, <%= @picture.artist %></p>
<!-- <img src="<%= @picture.url %>"> -->
<%= image_tag(@picture.url) %>